
/*********************************************************************
 * This file is automatically generated by mmir-plugins-export tools *
 *         Do not modify: ANY CHANGES WILL GET DISCARED              *
 *********************************************************************/

module.exports = {
  pluginName: "asrGoogleXhr",
  config: [
    /** OPTIONAL custom option: samplerate (Hz) for audio encoding, DEFAULT 44100 */
    "sampleRate",
    /** OPTIONAL number of n-best results that should (max.) be returned: integer, DEFAULT 1 */
    "results",
    /** credentials application key (MUST be set via configuration or options) */
    "appKey",
    /** OPTIONAL (see mmir-plugin-encoder-core)
     * @default "flac" */
    "encoder",
    /** the plugin/module which which will load/use this specific ASR implementation
     * @default mmir-plugin-encoder-core.js
     */
    "mod"
  ],
  defaultValues: {
    encoder: "flac",
    mod: "mmir-plugin-encoder-core.js"
  },
  remoteUrls: {
    baseUrl: "https://www.google.com"
  }
};
