
/*********************************************************************
 * This file is automatically generated by mmir-plugins-export tools *
 *         Do not modify: ANY CHANGES WILL GET DISCARED              *
 *********************************************************************/

module.exports = {
  pluginName: "asrGoogleXhr",
  config: [
    /** OPTIONAL number of n-best results that should (max.) be returned: integer of [1, 10] */
    "results",
    /** credentials application key (MUST be set via configuration or options) */
    "appKey",
    /** OPTIONAL
     * @default "flac" (see mmir-plugin-encoder-core) */
    "encoder"
  ],
  remoteUrls: {
    baseUrl: "https://www.google.com"
  }
};
